#!/usr/bin/env python3
"""WorkQuarry installer.

Copies the tracker *mechanism* (this repo / submodule) into a target repo's
harness-mandated locations, so `python tools/track.py ...`, the `.claude/skills/`,
and the `AGENTS.md` rules all resolve where the tools look for them.

The mechanism is the single source of truth. Vendored copies are GENERATED
artifacts: each carries a banner and must not be hand-edited. To improve the
tracker, edit files here (in the submodule), then re-run this installer.

Usage (from the consuming repo root, with WorkQuarry vendored as a submodule):
    python submodules/workquarry/install.py                 # install / update
    python submodules/workquarry/install.py --root .        # explicit target root
    python submodules/workquarry/install.py --check         # report drift, exit 1 if any
    python submodules/workquarry/install.py --dry-run       # show what would change

Instance data (tracker/issues, BACKLOG.md, DONE.md, decisions/*, config.json) is
never touched once it exists; only the mechanism is (re)written.
"""
import argparse, shutil, sys
from pathlib import Path

SRC = Path(__file__).resolve().parent
BANNER = ("GENERATED by the WorkQuarry installer — do not hand-edit. "
          "Edit the source in the workquarry submodule and re-run install.py.")
BEGIN, END = "<!-- workquarry:begin -->", "<!-- workquarry:end -->"

# canonical source -> path relative to the target repo root
MECHANISM = {
    "track.py": "tools/track.py",
    "process.md": "tracker/readme.md",
    "templates/issue.md": "tracker/issues/_template.md",
    "templates/decision.md": "tracker/decisions/_template.md",
    "skills/track-idea/SKILL.md": ".claude/skills/track-idea/SKILL.md",
    "skills/track-issue/SKILL.md": ".claude/skills/track-issue/SKILL.md",
    "skills/track-backlog/SKILL.md": ".claude/skills/track-backlog/SKILL.md",
    "skills/write-readme/SKILL.md": ".claude/skills/write-readme/SKILL.md",
}


def banner_for(dest: Path, text: str) -> str:
    """Add the GENERATED banner without breaking frontmatter or shebangs."""
    if dest.suffix == ".py":
        lines = text.splitlines(keepends=True)
        if lines and lines[0].startswith("#!"):
            return lines[0] + f"# {BANNER}\n" + "".join(lines[1:])
        return f"# {BANNER}\n" + text
    # markdown: keep frontmatter first (Claude Code needs SKILL.md to start with ---)
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            cut = end + len("\n---")
            return text[:cut] + f"\n\n<!-- {BANNER} -->\n" + text[cut:]
    return f"<!-- {BANNER} -->\n\n" + text


def strip_banner(text: str) -> str:
    # Exact inverse of banner_for's insertions (order matters: the frontmatter
    # chunk contains the no-frontmatter substring, so strip it first).
    return (text.replace(f"# {BANNER}\n", "")
                .replace(f"\n\n<!-- {BANNER} -->\n", "")
                .replace(f"<!-- {BANNER} -->\n\n", ""))


def inject_agents(root: Path, snippet: str, dry: bool) -> str:
    dest = root / "AGENTS.md"
    block = f"{BEGIN}\n{snippet.strip()}\n{END}\n"
    if dest.exists():
        text = dest.read_text(encoding="utf-8")
        if BEGIN in text and END in text:
            pre, rest = text.split(BEGIN, 1)
            _, post = rest.split(END, 1)
            new = pre + block + post
            action = "updated block in AGENTS.md"
        else:
            new = text.rstrip() + "\n\n" + block
            action = "appended block to AGENTS.md"
    else:
        new = "# AGENTS\n\n" + block
        action = "created AGENTS.md"
    if not dry:
        dest.write_text(new, encoding="utf-8")
    return action


def scaffold(root: Path, dry: bool) -> list[str]:
    done = []
    for d in ("tracker/issues", "tracker/decisions", "tools", ".claude/skills"):
        p = root / d
        if not p.exists():
            done.append(f"mkdir {d}")
            if not dry:
                p.mkdir(parents=True, exist_ok=True)
    cfg = root / "tracker" / "config.json"
    if not cfg.exists():
        done.append("tracker/config.json (from example - EDIT your areas)")
        if not dry:
            shutil.copyfile(SRC / "tracker" / "config.example.json", cfg)
    for name, seed in (("BACKLOG.md", "# Backlog — open items\n"),
                       ("DONE.md", "# Done — completed and dropped items\n\n"
                                   "Append-only, newest first.\n")):
        p = root / "tracker" / name
        if not p.exists():
            done.append(f"tracker/{name} (empty seed)")
            if not dry:
                p.write_text(seed, encoding="utf-8")
    return done


def do_install(root: Path, dry: bool) -> None:
    changes = scaffold(root, dry)
    for src_rel, dst_rel in MECHANISM.items():
        src, dst = SRC / src_rel, root / dst_rel
        content = banner_for(dst, (SRC / src_rel).read_text(encoding="utf-8"))
        if dst.exists() and dst.read_text(encoding="utf-8") == content:
            continue
        changes.append(("would write " if dry else "wrote ") + dst_rel)
        if not dry:
            dst.parent.mkdir(parents=True, exist_ok=True)
            dst.write_text(content, encoding="utf-8")
    changes.append(inject_agents(root, (SRC / "AGENTS-snippet.md").read_text(encoding="utf-8"), dry))
    print("\n".join(f"  {c}" for c in changes) or "  (nothing to do)")
    print(f"{'[dry-run] ' if dry else ''}WorkQuarry installed into {root}")


def do_check(root: Path) -> None:
    drift = []
    for src_rel, dst_rel in MECHANISM.items():
        dst = root / dst_rel
        if not dst.exists():
            drift.append(f"MISSING  {dst_rel}")
            continue
        want = (SRC / src_rel).read_text(encoding="utf-8")
        got = strip_banner(dst.read_text(encoding="utf-8"))
        if got != want:
            drift.append(f"DRIFTED  {dst_rel}  (hand-edited? edit the submodule instead)")
    if drift:
        print("\n".join(drift))
        sys.exit(1)
    print("OK - all vendored copies match the WorkQuarry source.")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--root", default=".", help="target repo root (default: cwd)")
    p.add_argument("--check", action="store_true", help="report drift, exit 1 if any")
    p.add_argument("--dry-run", action="store_true", help="show changes without writing")
    a = p.parse_args()
    root = Path(a.root).resolve()
    if a.check:
        do_check(root)
    else:
        do_install(root, a.dry_run)


if __name__ == "__main__":
    main()
