#!/usr/bin/env python3
"""WorkQuarry tracker helper. Issue frontmatter in <tracker>/issues/*.md is the
database; BACKLOG.md is a generated index; DONE.md is an append-only event log.

Areas and paths are NOT hardcoded: they come from tracker/config.json, discovered
by walking up from the current directory (falling back to this script's repo root).
That is what lets one copy of this file serve any repo.

Usage:
  python tools/track.py new --title "..." --area <area> [--type idea] [--priority ?]
                            [--effort ?] [--risk ?] [--status idea] [--sprint NAME]
                            [--links "a, b"] [--dry-run]
  python tools/track.py set ID [--status ready] [--priority p1] [--effort M]
                            [--risk low] [--sprint NAME|none] [--title "..."]
  python tools/track.py list [--status S] [--area A] [--type T] [--priority P]
                            [--sprint NAME] [--open] [--sort priority|id|status|sprint]
                            [--format table|csv]
  python tools/track.py close ID [--outcome "done (abc1234)"] [--dropped]
  python tools/track.py index      # regenerate BACKLOG.md from frontmatter
  python tools/track.py next-id    # print next available issue number

new/set/close regenerate BACKLOG.md automatically. Never hand-edit BACKLOG.md.
"""
import argparse, csv, datetime, io, json, re, sys
from pathlib import Path

FIELDS = ["id", "title", "type", "status", "priority", "effort", "risk",
          "area", "sprint", "created", "closed", "links"]
PRI_ORDER = {"p1": 1, "p2": 2, "p3": 3, "?": 4}
STATUS_ORDER = {"in-progress": 1, "ready": 2, "idea": 3, "done": 8, "dropped": 9}


def find_config() -> Path:
    """Locate tracker/config.json: search cwd upward, then this script's repo root."""
    here = Path.cwd()
    for base in (here, *here.parents):
        cfg = base / "tracker" / "config.json"
        if cfg.exists():
            return cfg
    cfg = Path(__file__).resolve().parent.parent / "tracker" / "config.json"
    if cfg.exists():
        return cfg
    sys.exit("workquarry: no tracker/config.json found. Run the installer or create one "
             "(see tracker/config.example.json).")


CONFIG_PATH = find_config()
CONFIG = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
ROOT = CONFIG_PATH.parent.parent
_paths = CONFIG.get("paths", {})
ISSUES = ROOT / _paths.get("issues", "tracker/issues")
BACKLOG = ROOT / _paths.get("backlog", "tracker/BACKLOG.md")
DONE = ROOT / _paths.get("done", "tracker/DONE.md")
AREAS = set(CONFIG.get("areas", []))


def today() -> str:
    return datetime.date.today().isoformat()


def next_num() -> int:
    nums = [int(m.group(1)) for f in ISSUES.glob("*-[0-9]*.md")
            if (m := re.search(r"-(\d+)\.md$", f.name))]
    return max(nums, default=0) + 1


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:  # some issue files arrive cp1252-encoded
        return path.read_text(encoding="cp1252")


def parse_frontmatter(path: Path) -> dict:
    text = read_text(path)
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    fm = {"_path": path}
    if not m:
        return fm
    for line in m.group(1).splitlines():
        if km := re.match(r"^(\w[\w-]*):\s*(.*)$", line):
            fm[km.group(1)] = km.group(2).strip().strip('"')
    return fm


def all_issues() -> list[dict]:
    return [parse_frontmatter(f) for f in sorted(ISSUES.glob("*-[0-9]*.md"))]


def set_field(path: Path, key: str, value: str) -> None:
    text = read_text(path)
    if re.search(rf"(?m)^{key}:", text):
        text = re.sub(rf"(?m)^{key}:.*$", f"{key}: {value}".rstrip(), text, count=1)
    else:  # insert before closing --- of frontmatter
        text = re.sub(r"(?m)^---$", f"{key}: {value}\n---", text.replace("---", "\x00", 1), count=1)
        text = text.replace("\x00", "---", 1)
    path.write_text(text, encoding="utf-8")


def sort_key(fm: dict):
    return (STATUS_ORDER.get(fm.get("status", ""), 5),
            PRI_ORDER.get(fm.get("priority", "?"), 4),
            fm.get("id", ""))


def open_issues() -> list[dict]:
    return [i for i in all_issues()
            if i.get("status") not in ("done", "dropped") and i.get("id")]


def regen_index() -> None:
    rows = sorted(open_issues(), key=sort_key)
    lines = [
        "# Backlog — open items",
        "",
        "<!-- GENERATED by tools/track.py — do not edit. Regenerate: python tools/track.py index -->",
        "",
        "One line per open issue; full detail in `issues/<id>.md`. Process: [readme.md](readme.md).",
        "Issue frontmatter is the source of truth; this file is a generated view",
        "(sorted by status, then priority). Filtered views: `python tools/track.py list --help`.",
        "",
        "| id | title | type | pri | effort | risk | area | status | sprint |",
        "|----|-------|------|-----|--------|------|------|--------|--------|",
    ]
    for i in rows:
        lines.append(
            f"| [{i['id']}](issues/{i['id']}.md) | {i.get('title','')} | {i.get('type','')} "
            f"| {i.get('priority','?')} | {i.get('effort','?')} | {i.get('risk','?')} "
            f"| {i.get('area','')} | {i.get('status','')} | {i.get('sprint','')} |")
    BACKLOG.write_text("\n".join(lines) + "\n", encoding="utf-8")


def cmd_new(a) -> None:
    if a.area not in AREAS:
        sys.exit(f"unknown area '{a.area}' (expected one of {sorted(AREAS)}; "
                 f"edit areas in {CONFIG_PATH})")
    iid = f"{a.area}-{next_num():03d}"
    links = "[" + ", ".join(s.strip() for s in a.links.split(",") if s.strip()) + "]" if a.links else "[]"
    def q(v): return f'"{v}"' if v == "?" else v
    fm = (f"---\nid: {iid}\ntitle: {a.title}\ntype: {a.type}\nstatus: {a.status}\n"
          f"priority: {q(a.priority)}\neffort: {q(a.effort)}\nrisk: {q(a.risk)}\n"
          f"area: {a.area}\nsprint: {a.sprint}\ncreated: {today()}\nclosed:\nlinks: {links}\n---\n")
    if a.dry_run:
        print(f"would create {iid}\n{fm}")
        return
    path = ISSUES / f"{iid}.md"
    path.write_text(fm, encoding="utf-8")
    regen_index()
    print(f"{iid}\n{path}")


def cmd_set(a) -> None:
    path = ISSUES / f"{a.id}.md"
    if not path.exists():
        sys.exit(f"no such issue: {a.id}")
    changes = {k: v for k, v in
               [("status", a.status), ("priority", a.priority), ("effort", a.effort),
                ("risk", a.risk), ("title", a.title),
                ("sprint", "" if a.sprint == "none" else a.sprint)]
               if v is not None}
    if not changes:
        sys.exit("nothing to set")
    for k, v in changes.items():
        set_field(path, k, f'"{v}"' if v == "?" else v)
    regen_index()
    print(f"{a.id}: " + ", ".join(f"{k}={v or '(cleared)'}" for k, v in changes.items()))


def cmd_close(a) -> None:
    path = ISSUES / f"{a.id}.md"
    if not path.exists():
        sys.exit(f"no such issue: {a.id}")
    status = "dropped" if a.dropped else "done"
    set_field(path, "status", status)
    set_field(path, "closed", today())
    fm = parse_frontmatter(path)
    done = DONE.read_text(encoding="utf-8").splitlines()
    entry = f"- {today()} — [{a.id}](issues/{a.id}.md) — {fm.get('title', a.id)} — {a.outcome or status}"
    for i, line in enumerate(done):
        if line.startswith("- "):
            done.insert(i, entry)
            break
    else:
        done.append(entry)
    DONE.write_text("\n".join(done) + "\n", encoding="utf-8")
    regen_index()
    print(f"{a.id} {status}")


def cmd_list(a) -> None:
    rows = open_issues() if a.open else [i for i in all_issues() if i.get("id")]
    for attr, key in [("status", "status"), ("area", "area"), ("type", "type"),
                      ("priority", "priority"), ("sprint", "sprint")]:
        if (want := getattr(a, attr)) is not None:
            rows = [r for r in rows if r.get(key, "") == want]
    keys = {"priority": lambda r: (PRI_ORDER.get(r.get("priority", "?"), 4), r.get("id", "")),
            "id": lambda r: r.get("id", ""),
            "status": sort_key,
            "sprint": lambda r: (r.get("sprint", "") == "", r.get("sprint", ""), sort_key(r)),
            "created": lambda r: (r.get("created", ""), r.get("id", ""))}
    rows = sorted(rows, key=keys[a.sort])
    cols = ["id", "title", "type", "priority", "effort", "risk", "area", "status", "sprint", "created"]
    if a.format == "csv":
        buf = io.StringIO()
        w = csv.writer(buf, lineterminator="\n")
        w.writerow(cols)
        for r in rows:
            w.writerow([r.get(c, "") for c in cols])
        print(buf.getvalue(), end="")
    else:
        widths = [max(len(c), *(len(r.get(c, "")) for r in rows)) if rows else len(c) for c in cols]
        print("  ".join(c.ljust(w) for c, w in zip(cols, widths)))
        for r in rows:
            print("  ".join(r.get(c, "").ljust(w) for c, w in zip(cols, widths)))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)

    n = sub.add_parser("new")
    n.add_argument("--title", required=True)
    n.add_argument("--area", required=True)
    n.add_argument("--type", default="idea",
                   choices=["feature", "debt", "bug", "idea", "problem", "retire"])
    n.add_argument("--status", default="idea", choices=["idea", "ready", "in-progress"])
    n.add_argument("--priority", default="?", choices=["p1", "p2", "p3", "?"])
    n.add_argument("--effort", default="?", choices=["S", "M", "L", "?"])
    n.add_argument("--risk", default="?", choices=["low", "med", "high", "?"])
    n.add_argument("--sprint", default="")
    n.add_argument("--links", default="")
    n.add_argument("--dry-run", action="store_true")
    n.set_defaults(func=cmd_new)

    s = sub.add_parser("set")
    s.add_argument("id")
    s.add_argument("--status", choices=["idea", "ready", "in-progress"])
    s.add_argument("--priority", choices=["p1", "p2", "p3", "?"])
    s.add_argument("--effort", choices=["S", "M", "L", "?"])
    s.add_argument("--risk", choices=["low", "med", "high", "?"])
    s.add_argument("--sprint", help="sprint name, or 'none' to clear")
    s.add_argument("--title")
    s.set_defaults(func=cmd_set)

    l = sub.add_parser("list")
    l.add_argument("--status")
    l.add_argument("--area")
    l.add_argument("--type")
    l.add_argument("--priority")
    l.add_argument("--sprint")
    l.add_argument("--open", action="store_true", help="open items only")
    l.add_argument("--sort", default="status", choices=["priority", "id", "status", "sprint", "created"])
    l.add_argument("--format", default="table", choices=["table", "csv"])
    l.set_defaults(func=cmd_list)

    c = sub.add_parser("close")
    c.add_argument("id")
    c.add_argument("--outcome", default="")
    c.add_argument("--dropped", action="store_true")
    c.set_defaults(func=cmd_close)

    sub.add_parser("index").set_defaults(func=lambda a: regen_index())
    sub.add_parser("next-id").set_defaults(func=lambda a: print(next_num()))

    a = p.parse_args()
    a.func(a)


if __name__ == "__main__":
    main()
